version: '3.5'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: "host.docker.internal"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "10051:10051"

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      DB_SERVER_HOST: "host.docker.internal"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "8087:8080" #веб-интерфейс Zabbix -> 8087 - мой хост, 8080 - внутри контейнера
    depends_on:
      - zabbix-server

volumes:
  postgres-data:
